linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - golint
    - ifshort
    - interfacer
    - lll
    - maligned
    - nlreturn
    - scopelint
    - varnamelen
    - wsl

linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US
