linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - ifshort
    - lll
    - nlreturn
    - wsl

linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
