language: go

go:
  - stable

env:
  - GO111MODULE=on

before_install:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u github.com/go-critic/go-critic/...

install:
  - go mod download

script:
  - make lint
  - make test
  - make
